### ISSUE TITLE
Using checkbox with label in other components

### ISSUE THREAD

**Issue by vadzim-revolist** [fogfish/react-dress-code#1]
https://github.com/fogfish/react-dress-code/blob/aca32b97b8e050ba43bdee07e2e3ccd6c6659ba8/src/atoms/input.js#L26

To link a label and a checkbox input one have to specify an id. But if a checkbox is a part of other component than it is difficult to assign ids unique to a whole form/document.
This can be solved in Checkbox component by creating Id when Checkbox is instantiated and e.g. placing it in the component state:
```javascript
let cbId
withState('id', 'setId', props => props.id || `dc_cb_${++cbId}`)(Checkbox)
```

**Comment by fogfish** [comment]
fixed.
